# Header
menu:
  Home: /
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- recent_posts
- category
- tagcloud



# Miscellaneous
google_analytics: UA-62603909-1
favicon: /favicon.png
twitter: piotrbuda 
google_plus:
fb_admins:
fb_app_id: